# Generated by Django 5.0.3 on 2024-03-27 20:33

import book_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(validators=[django.core.validators.MaxLengthValidator(100), book_app.validators.validate_title])),
                ('author', models.CharField(validators=[django.core.validators.MaxLengthValidator(100), book_app.validators.validate_author])),
                ('isbn', models.CharField(unique=True, validators=[django.core.validators.MaxLengthValidator(14), book_app.validators.validate_isbn])),
                ('genre', models.CharField(validators=[django.core.validators.MaxLengthValidator(100), book_app.validators.validate_genre])),
                ('published_date', models.DateField()),
            ],
        ),
    ]
